### ISSUE TITLE
Fix deprecation warnings

### ISSUE THREAD

**Issue by icemac** [zopefoundation/five.formlib#8]
Zope 5 will drop support for some functions used in this package:

```
/.../five.formlib/src/five/formlib/__init__.py:63: DeprecationWarning: processInputs() is deprecated and will be removed in Zope 5.0. If your view implements IBrowserPage, similar processing is now executed automatically.
  processInputs(self.request, self.charsets)
/.../five.formlib/src/five/formlib/__init__.py:64: DeprecationWarning: setPageEncoding() is deprecated and will be removed in Zope 5.0. It is recommended to let the ZPublisher use the default_encoding. Please consider setting default-zpublisher-encoding to utf-8.
  setPageEncoding(self.request)
/.../Products/Five/browser/decode.py:81: DeprecationWarning: processInputValue() is deprecated and will be removed in Zope 5.0.
```

They should be replaced.

**Comment by d-maurer** [comment]
Michael Howitz wrote at 2019-3-1 07:19 +0000:
>Zope 5 will drop support for some functions used in this package:
>
>```
>/.../five.formlib/src/five/formlib/__init__.py:63: DeprecationWarning: processInputs() is deprecated and will be removed in Zope 5.0. If your view implements IBrowserPage, similar processing is now executed automatically.
>  processInputs(self.request, self.charsets)
>/.../five.formlib/src/five/formlib/__init__.py:64: DeprecationWarning: setPageEncoding() is deprecated and will be removed in Zope 5.0. It is recommended to let the ZPublisher use the default_encoding. Please consider setting default-zpublisher-encoding to utf-8.
>  setPageEncoding(self.request)
>/.../Products/Five/browser/decode.py:81: DeprecationWarning: processInputValue() is deprecated and will be removed in Zope 5.0.
>```
>
>They should be replaced.

I tried to remove those functions (in fact, they should no longer be
necessary).

However, this caused the tests for Python 2.7 to raise 3 warnings:
./home/dieter/tmp/xmlsec2/python/local/lib/python2.7/site-packages/zope/formlib/textwidgets.py:530: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if input == self._missing:

/home/dieter/tmp/xmlsec2/python/local/lib/python2.7/site-packages/zope/formlib/textwidgets.py:135: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if self.convert_missing_value and input == self._missing:

/home/dieter/tmp/xmlsec2/python/local/lib/python2.7/site-packages/zope/formlib/widget.py:447: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if input == self._missing:

rather than a single one:

textwidgets.py:135: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if self.convert_missing_value and input == self._missing:

I.e. the 1. and 3. warning have been avoided by those functions.


Apparently, under Python 2.7, the default import value handling of
`Products.Five.browser.BrowserView` is less good than the
explicit calls of `processInputs` and `setPageEncoding` --
and even the latter is not perfect (still giving one warning).


The Python 3 tests do not produce warnings without those
functions (apart from a stupid Python `ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__`
warning). Looks, like those functions are really no longer necessary
for Python 3.

**Comment by icemac** [comment]
@d-maurer Thank you for your analysis. So let's keep using these functions until Python 2 support ist dropped.
